In [24]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn.linear_model as skl_lm
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, classification_report, precision_score
from sklearn import preprocessing
from sklearn import neighbors

import statsmodels.api as sm
import statsmodels.formula.api as smf

In [33]:
def mapping(x):
    if x=='good':
        return 1
    elif x == 'bad':
        return 0
    else:
        return -1

ion = pd.read_csv('Ionosphere.csv', na_values='?')
ion['Class1'] = ion.Class.apply(mapping)
ion.Class1.factorize()[0]
ion.info()
ion.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  351 non-null    int64
 1   V1          351 non-null    int64
 2   V2          351 non-null    int64
 3   V3          351 non-null    float64
 4   V4          351 non-null    float64
 5   V5          351 non-null    float64
 6   V6          351 non-null    float64
 7   V7          351 non-null    float64
 8   V8          351 non-null    float64
 9   V9          351 non-null    float64
 10  V10         351 non-null    float64
 11  V11         351 non-null    float64
 12  V12         351 non-null    float64
 13  V13         351 non-null    float64
 14  V14         351 non-null    float64
 15  V15         351 non-null    float64
 16  V16         351 non-null    float64
 17  V17         351 non-null    float64
 18  V18         351 non-null    float64
 19  V19         351 non-null    float64
 20  V20         351 non-null    float64
 21  V21         351 non-null    float64
 22  V22         351 non-null    float64
 23  V23         351 non-null    float64
 24  V24         351 non-null    float64
 25  V25         351 non-null    float64
 26  V26         351 non-null    float64
 27  V27         351 non-null    float64
 28  V28         351 non-null    float64
 29  V29         351 non-null    float64
 30  V30         351 non-null    float64
 31  V31         351 non-null    float64
 32  V32         351 non-null    float64
 33  V33         351 non-null    float64
 34  V34         351 non-null    float64
 35  Class       351 non-null    object
 36  Class1      351 non-null    int64
dtypes: float64(32), int64(4), object(1)
memory usage: 101.6+ KB

,Unnamed: 0,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V27,V28,V29,V30,V31,V32,V33,V34,Class,Class1
0,1,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,...,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,good,0
1,2,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,...,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,bad,1
2,3,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,...,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,good,0
3,4,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,...,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,bad,1
4,5,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,...,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,good,0

In [34]:
ion_train, ion_test = train_test_split(ion, test_size=0.3, random_state=42)
est = smf.logit('Class1 ~ V6 + V7 + V8 + V9 + V10 + V11 + V12', ion_train).fit()
est.summary2().tables[1]

Optimization terminated successfully.
         Current function value: 0.448957
         Iterations 6

              Coef.  Std.Err.         z         P>|z|    [0.025    0.975]
Intercept  1.570879  0.346329  4.535805  5.738427e-06  0.892087  2.249671
V6         0.002950  0.400974  0.007358  9.941290e-01 -0.782944  0.788845
V7        -2.376640  0.458402 -5.184616  2.164601e-07 -3.275092 -1.478188
V8        -2.164808  0.434343 -4.984103  6.225002e-07 -3.016104 -1.313512
V9        -1.575580  0.520582 -3.026573  2.473433e-03 -2.595903 -0.555258
V10       -0.341267  0.411712 -0.828897  4.071628e-01 -1.148207  0.465674
V11        0.159818  0.438339  0.364600  7.154099e-01 -0.699310  1.018946
V12       -0.235630  0.405169 -0.581559  5.608636e-01 -1.029746  0.558487

In [36]:
pred = est.predict(ion_test)

threshold = 0.5

157    0.401934
342    0.156967
316    0.166035
234    0.149397
155    0.189133
         ...
258    0.229166
329    0.128368
335    0.095167
19     0.512368
139    0.343665
Length: 106, dtype: float64

In [38]:
"""
predictions = est.predict(ion_test)

# Convert probabilities to binary predictions (0 or 1) based on a threshold (e.g., 0.5)
threshold = 0.5
binary_predictions = (predictions > threshold).astype(int)

# Calculate precision score (you can use other metrics as well)
precision = precision_score(ion_test['Class1'], binary_predictions)

# Print the precision score and other relevant metrics
print(f"Precision Score: {precision}")
print("Confusion Matrix:")
print(confusion_matrix(ion_test['Class1'], binary_predictions))
print("Classification Report:")
print(classification_report(ion_test['Class1'], binary_predictions))
"""

'\npredictions = est.predict(ion_test)\n\n# Convert probabilities to binary predictions (0 or 1) based on a threshold (e.g., 0.5)\nthreshold = 0.5\nbinary_predictions = (predictions > threshold).astype(int)\n\n# Calculate precision score (you can use other metrics as well)\nprecision = precision_score(ion_test[\'Class1\'], binary_predictions)\n\n# Print the precision score and other relevant metrics\nprint(f"Precision Score: {precision}")\nprint("Confusion Matrix:")\nprint(confusion_matrix(ion_test[\'Class1\'], binary_predictions))\nprint("Classification Report:")\nprint(classification_report(ion_test[\'Class1\'], binary_predictions))\n'